#CQ 1: Give me all substances that have a common active moiety <active moiety x>.

prefix idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
prefix rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:        <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

select distinct ?substanceUri ?substanceType ?substanceLabel

where {
  	# Need to find all substances that are Substances or it's subclasses
  	?substanceType rdfs:subClassOf* idmp-sub:Substance .
	  ?substanceUri a ?substanceType .
  	?substanceUri skos:prefLabel ?substanceLabel .
  	
  	# Link the substance to the active moiety we are looking for via its label.  
  	# Note that rdfs:labels are all lower case by convention and IDMP Ontology standards.
  	?substanceUri idmp-sub:hasActiveMoiety ?activeMoiety .
  	?activeMoiety skos:prefLabel "AMLODIPINE" .
}
