search_config:
  search_descriptions:
    - 'http://www.w3.org/2004/02/skos/core#definition'
    - 'http://purl.org/dc/terms/abstract'
  fuzzy_distance: 3
  reindex_on_start: true
  find_properties:
    - label: RDFS label
      identifier: rdfs_label
      iri: http://www.w3.org/2000/01/rdf-schema#label
    - label: SKOS definition
      identifier: skos_definition
      iri: http://www.w3.org/2004/02/skos/core#definition
    - label: OMG explanatory note
      identifier: omg_explanatoryNote
      iri: https://www.omg.org/spec/Commons/AnnotationVocabulary/explanatoryNote
    - label: SKOS Note
      identifier: skos_note
      iri: http://www.w3.org/2004/02/skos/core#note
    - label: PURL description
      identifier: purl_description
      iri: http://purl.org/dc/terms/description
    - label: OMG synonym
      identifier: omg_synonym
      iri: https://www.omg.org/spec/Commons/AnnotationVocabulary/synonym
    - label: SKOS example
      identifier: skos_example
      iri: http://www.w3.org/2004/02/skos/core#example
    - label: OMG usage note
      identifier: omg_usageNote
      iri: https://www.omg.org/spec/Commons/AnnotationVocabulary/usageNote
    - label: SKOS scope note
      identifier: omg_scopeNote
      iri: http://www.w3.org/2004/02/skos/core#scopeNote
    - label: OMG symbol
      identifier: omg_symbol
      iri: https://www.omg.org/spec/Commons/AnnotationVocabulary/symbol
    - label: has text value
      identifier: omg_text_value
      iri: https://www.omg.org/spec/Commons/TextDatatype/hasTextValue
