prefix cmns-pts:    <https://www.omg.org/spec/Commons/PartiesAndSituations/>
prefix idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
prefix rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:        <http://www.w3.org/2000/01/rdf-schema#>
prefix skos:        <http://www.w3.org/2004/02/skos/core#>

select distinct ?activeMoietySubstance ?activeMoietyType ?moietySubstanceLabel
where {

    ?activeMoietySubstance cmns-pts:playsRole ?activeMoietyRole ;
                    rdf:type ?activeMoietyType ;
                    rdfs:label ?moietySubstanceLabel .
    ?activeMoietyRole rdf:type idmp-sub:MoietyRole ;
                    skos:related ?targetSubstance .
    ?targetSubstance rdfs:label #substance_label# .
}