# What is the basis of strength for <substance x> in <product y>?

prefix cmns-col:    <https://www.omg.org/spec/Commons/Collections/>
prefix cmns-des:    <https://www.omg.org/spec/Commons/Designators/>
prefix cmns-pts:    <https://www.omg.org/spec/Commons/PartiesAndSituations/>
prefix idmp-mprd:   <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/>
prefix idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
prefix rdfs:        <http://www.w3.org/2000/01/rdf-schema#> 

SELECT distinct ?activeMoiety ?activeMoietyLabel from <http://localhost:3030/idmp/data/mvp> from <http://localhost:3030/idmp/data/iso>
WHERE {
  	?productUri rdfs:label <product_y_label> #"Amlodipine EMC 5 mg tablet".
  	?productUri a idmp-mprd:PharmaceuticalProduct .
   	?productUri cmns-col:comprises ?substance .
	?substance rdfs:label  <substance_x_label> #"amlodipine mesylate monohydrate" .
  	?substance idmp-sub:hasActiveMoiety ?activeMoiety .
  	?activeMoiety rdfs:label ?activeMoietyLabel .
}