# CQ 4: Which EV code (future SMS code) does the substance <substance> have?

PREFIX cmns-id: 	<https://www.omg.org/spec/Commons/Identifiers/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
prefix cmns-ra:   	<https://www.omg.org/spec/Commons/RegistrationAuthorities/>
prefix cmns-txt:    <https://www.omg.org/spec/Commons/TextDatatype/>
prefix idmp-ra: <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-RegistrationAuthorities/> 
prefix idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
prefix rdfs:        <http://www.w3.org/2000/01/rdf-schema#> 

SELECT ?substance ?evCode
WHERE {
    # Find the Subtance and what it is identified by
    ?type rdfs:subClassOf* idmp-sub:Substance .
    ?substance rdf:type ?type;
    		cmns-id:isIdentifiedBy ?identifier ;
  			skos:prefLabel #substance_label# .

    # Find the Identifier that is registered in the eXtended EudraVigilance Medicinal Product Dictionary
    ?identifier rdf:type  cmns-ra:RegisteredIdentifier;
             cmns-txt:hasTextValue ?evCode ;
             cmns-ra:isRegisteredIn idmp-ra:EuropeanMedicinesAgencyRegistrationAuthority
}