# CQ 8: Which investigational medicinal products are related to this manufactured item?

prefix cmns-col:    <https://www.omg.org/spec/Commons/Collections/>
prefix cmns-dsg:    <https://www.omg.org/spec/Commons/Designators/>
prefix cmns-pts:    <https://www.omg.org/spec/Commons/PartiesAndSituations/>
prefix idmp-mprd:   <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/>
prefix idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
prefix rdfs:        <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT distinct ?investigationalMedinicalProduct

WHERE {
  	# Find Manufactured Items and that have the role of Investigational Medicinal product
	?manufacturedItemType rdfs:subClassOf* idmp-sub:ManufacturedItem .
  	?manufacturedItem rdf:type ?manufacturedItemType .
  	?manufacturedItem rdfs:label # medical product label e.g. "Norvasc medicinal product" .
    ?investigationalMedinicalProduct cmns-pts:isPlayedBy ?manufacturedItem .
    ?investigationalMedinicalProduct rdf:type idmp-mprd:InvestigationalMedicinalProduct .
}