PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

##
# banner We be aware when an OWL class is used as an individual.

SELECT DISTINCT (concat ("WARN: Individual ", str(?individual), " is used as a class.") AS ?error) ?individual
WHERE
{
    ?individual rdf:type owl:NamedIndividual.
    {?individual rdfs:subClassOf | owl:unionOf | owl:intersectionOf | owl:disjointWith | owl:unionOf | owl:disjointUnionOf | owl:equivalentClass | owl:hasKey | owl:hasSelf | owl:hasValue ?resource.}
    UNION
    {?resource rdfs:subClassOf | rdfs:domain | rdfs:range | owl:equivalentClass ?individual.}
    FILTER regex(str(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)
}
ORDER BY ?individual
