prefix afn:   <http://jena.apache.org/ARQ/function#>

##
# banner We should avoid opaque IRIs

SELECT DISTINCT ?warn ?resource
WHERE 
{
  ?resource ?property ?object.
  FILTER (REGEX(afn:localname(?resource), "(\\d\\d\\d+$)|([^A-Za-z][A-Za-z][^A-Za-z])"))
  FILTER (REGEX(str(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>))
  BIND (concat ("WARN: IRI ", STR(?resource), " may be opaque ") AS ?warn)
}
