prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

##
# banner Labels should be unique across all ontologies for all resources.


SELECT DISTINCT (concat ("ERROR: prefLabel ", str(?prefLabel), " names multiple resources.") AS ?error)
WHERE
{
  ?resource skos:prefLabel ?prefLabel.
  FILTER NOT EXISTS {?resource owl:deprecated "true"^^xsd:boolean} .
	FILTER regex(str(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)
}
GROUP BY ?prefLabel
HAVING (COUNT(?resource) > 1)
