#CQ 1: Give me all substances that have a common active moiety <active moiety x>.
# Intended to run on data from AmlodipineExample.rdf

prefix idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
prefix rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:        <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?substanceUri ?substanceType ?substanceLabel

where {
	# Bind the name we want into a variable 
	BIND(cq_1_parameter_1 AS ?activeMoietyLabel )

  	# Need to find all substances that are Substances or it's subclasses
  	?substanceType rdfs:subClassOf* idmp-sub:Substance .
	  ?substanceUri a ?substanceType .
  	?substanceUri rdfs:label ?substanceLabel .
  	
  	# Link the substance to the active moiety we are looking for via its label.  
  	# Note that rdfs:labels are all lower case by convention and IDMP Ontology standards.
  	?substanceUri idmp-sub:hasActiveMoiety ?activeMoiety .
  	?activeMoiety rdfs:label ?activeMoietyLabel .
}