
# CQ03.1: What is the basis of strength for <substance x> in <product y>? (FOR PROTEGE)

prefix cmns-dsg:    <https://www.omg.org/spec/Commons/Designators/>
prefix idmp-mprd:   <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/>
prefix idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
prefix idmp-ucum: 	<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Extensions/UnifiedCodeForUnitsOfMeasure/>
prefix rdfs:        <http://www.w3.org/2000/01/rdf-schema#> 
prefix cmns-qtu: <https://www.omg.org/spec/Commons/QuantitiesAndUnits/>

SELECT distinct ?referenceSubstance ?referenceSubstanceLabel ?strengthNumeratorValue ?strengthNumeratorUnitLabel ?strengthDenominatorValue ?strengthDenominatorUnitLabel

WHERE {
    BIND("Norvasc" AS ?productLabel )
    BIND(cq_3-1b_parameter_1 AS ?substanceLabel)
  
  	# Start with the pharmaceutical product and link to its active ingredient from the product constituency
  	?pharmaceuticalProduct rdfs:label ?productLabel .
  	?productConstituency cmns-dsg:defines ?pharmaceuticalProduct .
	?productConstituency idmp-mprd:hasActiveIngredient ?activeIngredient .
  
  	# Get the reference substance and strength from the active ingredient
  	?activeIngredient idmp-mprd:hasReferenceSubstance ?referenceSubstance .
  	?referenceSubstance rdfs:label ?referenceSubstanceLabel .
  
  	# Get the Numerator and  Denominator information from the reference strength
  	?activeIngredient idmp-mprd:hasReferenceStrength ?referenceStrength .
  	?referenceStrength cmns-qtu:hasDenominator ?strengthDenominator .
  	?strengthDenominator cmns-qtu:hasNumericValue ?strengthDenominatorValue .
  	?strengthDenominator cmns-qtu:hasMeasurementUnit ?strengthDenominatorUnit .
    ?referenceStrength cmns-qtu:hasNumerator ?strengthNumerator .  
  	?strengthNumerator cmns-qtu:hasNumericValue ?strengthNumeratorValue .
  	?strengthNumerator cmns-qtu:hasMeasurementUnit ?strengthNumeratorUnit .
  	?strengthNumeratorUnit rdfs:label ?strengthNumeratorUnitLabel .
  	?strengthDenominatorUnit rdfs:label ?strengthDenominatorUnitLabel .

}

