# UC1-CQ 7: Which manufactured items contain <$SUBSTANCE> as ingredient of type “active”?

PREFIX cmns-dsg:    <https://www.omg.org/spec/Commons/Designators/>
PREFIX cmns-pts:    <https://www.omg.org/spec/Commons/PartiesAndSituations/>
PREFIX idmp-mprd:   <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/>
PREFIX idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT distinct ?ManufacturedItem (SAMPLE(?ManufacturedItemLabel) AS ?ManufacturedItemName)

WHERE {
    # Bind Variable substance <$Substance>
	# Example for AMPLODIPINE: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>
  	# Example for Terlipressin: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinAcetate>
    BIND(  uc1_cq7_parameter_1 AS $SUBSTANCE )

  	# Find Manufactured Items
	?ManufacturedItem a/rdfs:subClassOf* idmp-sub:ManufacturedItem ;
		cmns-dsg:isDefinedIn [
			idmp-mprd:hasActiveIngredient [
				cmns-pts:isPlayedBy $SUBSTANCE
			]
		] .

    # Optionally, get the name of the manufactured item
    OPTIONAL{?ManufacturedItem  rdfs:label  ?ManufacturedItemLabel }
 
} GROUP BY ?ManufacturedItem
