# UC1-CQ 5: In which clinical trials were the authorized medicinal products <$MedicinalProduct> administered?

PREFIX idmp-mprd: <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?ClinicalTrial (SAMPLE(?ClinicalTrialLabel) AS ?ClinicalTrialName)

WHERE {

  # Bind Variable authorized medicinal products  <$MedicinalProduct>
  # Example for European Union Clinical Trials Register: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/EuropeanUnionClinicalTrialsRegister/AliskirenAsInvestigationalMedicinalProduct>
  BIND(uc1_cq5_parameter_1 AS $MedicinalProduct )
  
  # Find clinical trials that manages the administration of $MedicinalProduct
  ?ClinicalTrial a idmp-mprd:ClinicalTrial ;
                  idmp-mprd:managesAdministrationOf ?MedicinalProduct .

  # Optionally, get the name of the clinical trial
  OPTIONAL{?ClinicalTrial  rdfs:label  ?ClinicalTrialLabel }

} GROUP BY ?ClinicalTrial