#UC2-CQ 1a: In which products (as active, excipient, packaging) is substance <$TargetSubstance> found?

PREFIX cmns-dsg:    <https://www.omg.org/spec/Commons/Designators/>
PREFIX cmns-rlcmp:    <https://www.omg.org/spec/Commons/RolesAndCompositions/>
PREFIX idmp-mprd:   <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/>
PREFIX idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
PREFIX rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?Product (SAMPLE(?ProductLabel) AS ?ProductName) 

WHERE {
    # Bind Variable substance <$TargetSubstance>
	# Example for AMPLODIPINE: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>
    BIND( uc2_cq1a_parameter_1 AS $TargetSubstance )

    [] cmns-dsg:defines ?Product ;
    $Role [
        cmns-rlcmp:isPlayedBy $TargetSubstance
    ] .
  
      # Make sure that we only return actual substances
    ?Product a/rdfs:subClassOf* idmp-mprd:ProductSpecification .
     
    # Optionally, get the name of the substance
    OPTIONAL{?Product  rdfs:label  ?ProductLabel }

} 
GROUP BY ?Product
ORDER BY ?Product