#UC2-CQ 1b: In which Stock Keeping Units is substance <$Substance> used?

PREFIX idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
PREFIX rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cmns-prd: 	<https://www.omg.org/spec/Commons/ProductsAndServices/>
PREFIX cmns-dsg:   <https://www.omg.org/spec/Commons/Designators/>
PREFIX cmns-col: <https://www.omg.org/spec/Commons/Collections/>
PREFIX cmns-rlcmp: <https://www.omg.org/spec/Commons/RolesAndCompositions/>
PREFIX idmp-mprd: <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/>


SELECT DISTINCT ?StockKeepingUnit (SAMPLE(?StockKeepingUnitLabel) AS ?StockKeepingUnitName)
WHERE {
    # Bind Variable substance <$Substance>
	# Example for AMLODIPINE: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine>
    BIND( uc2_cq1b_parameter_1 AS $Substance )
	{
		# Find SKUs where the a packaging is comprised of the substance, which is contained in the packaged medicinal product
		?StockKeepingUnit a cmns-prd:StockKeepingUnit ;
                    cmns-dsg:denotes [ idmp-mprd:contains [cmns-col:comprises $Substance] ] .
						
		# Make sure that we only return actual substances
		?StockKeepingUnit a/rdfs:subClassOf* cmns-prd:StockKeepingUnit .

		# Optionally, get the name of the substance
		OPTIONAL{?StockKeepingUnit  rdfs:label  ?StockKeepingUnitLabel }     
  } union {
		# Find SKUs where an intermediate packaging within the SKU's packaging is comprised of the substance (1-step)
		?StockKeepingUnit a cmns-prd:StockKeepingUnit ;
			cmns-dsg:denotes  [ idmp-mprd:contains [ idmp-mprd:contains [
					cmns-col:comprises $Substance
				]
      ] ].

		# Make sure that we only return actual substances
		?StockKeepingUnit a/rdfs:subClassOf* cmns-prd:StockKeepingUnit .

		# Optionally, get the name of the substance
		OPTIONAL{?StockKeepingUnit  rdfs:label  ?StockKeepingUnitLabel }
  } union {
		# Find SKUs where an intermediate packaging within the SKU's packaging is comprised of the substance (2-step)
		?StockKeepingUnit a cmns-prd:StockKeepingUnit ;
			cmns-dsg:denotes  [ idmp-mprd:contains [ idmp-mprd:contains [ 
					idmp-mprd:contains
					[
						cmns-col:comprises $Substance
					]		
			  	]
        ] ] .
		# Make sure that we only return actual substances
		?StockKeepingUnit a/rdfs:subClassOf* cmns-prd:StockKeepingUnit .

		# Optionally, get the name of the substance
		OPTIONAL{?StockKeepingUnit  rdfs:label  ?StockKeepingUnitLabel }
  } union {
     	# Find SKUs where a substance is used in the pharmaceutical product contained in an intermediate packaging (1-step)
		?StockKeepingUnit a cmns-prd:StockKeepingUnit ;
			cmns-dsg:denotes $PackagedMedicinalProduct .
    	?PackagedMedicinalProduct idmp-mprd:contains $OuterPackaging .
      	$OuterPackaging idmp-mprd:contains $IntermediatePackaging .
    	$IntermediatePackaging idmp-mprd:contains $PharmaceuticalProduct . 
    	$PharmaceuticalProductComposition cmns-dsg:defines $PharmaceuticalProduct .
    	$PharmaceuticalProductComposition idmp-mprd:hasActiveIngredient[
			cmns-rlcmp:isPlayedBy $Substance
		] .
		# Make sure that we only return actual substances
		?StockKeepingUnit a/rdfs:subClassOf* cmns-prd:StockKeepingUnit .

		# Optionally, get the name of the substance
		OPTIONAL{?StockKeepingUnit  rdfs:label  ?StockKeepingUnitLabel }

 } union {
       	# Find SKUs where a substance is used in the pharmaceutical product contained in an intermediate packaging (2-step)
		?StockKeepingUnit a cmns-prd:StockKeepingUnit ;
			cmns-dsg:denotes $PackagedMedicinalProduct .
    	?PackagedMedicinalProduct idmp-mprd:contains $OuterPackaging .
      	$OuterPackaging idmp-mprd:contains $InnerPackaing .
		$InnerPackaing 	idmp-mprd:contains $IntermediatePackaging .
    	$IntermediatePackaging idmp-mprd:contains $PharmaceuticalProduct . 
    	$PharmaceuticalProductComposition cmns-dsg:defines $PharmaceuticalProduct .
    	$PharmaceuticalProductComposition idmp-mprd:hasActiveIngredient[
			cmns-rlcmp:isPlayedBy $Substance
		] .
		# Make sure that we only return actual substances
		?StockKeepingUnit a/rdfs:subClassOf* cmns-prd:StockKeepingUnit .

		# Optionally, get the name of the substance
		OPTIONAL{?StockKeepingUnit  rdfs:label  ?StockKeepingUnitLabel }
  } union {
     	# Find SKUs where a substance is an active moiety for a substance used in the pharmaceutical product contained in an intermediate packaging (1-step)
		?StockKeepingUnit a cmns-prd:StockKeepingUnit ;
			cmns-dsg:denotes $PackagedMedicinalProduct .
    	?PackagedMedicinalProduct idmp-mprd:contains $OuterPackaging .
      	$OuterPackaging idmp-mprd:contains $IntermediatePackaging .
    	$IntermediatePackaging idmp-mprd:contains $PharmaceuticalProduct . 
    	$PharmaceuticalProductComposition cmns-dsg:defines $PharmaceuticalProduct .
    	$PharmaceuticalProductComposition idmp-mprd:hasActiveIngredient[
			cmns-rlcmp:isPlayedBy [ 
				^idmp-sub:isActiveMoietyOf|idmp-sub:hasActiveMoiety $Substance 
			]
		] .
		# Make sure that we only return actual substances
		?StockKeepingUnit a/rdfs:subClassOf* cmns-prd:StockKeepingUnit .

		# Optionally, get the name of the substance
		OPTIONAL{?StockKeepingUnit  rdfs:label  ?StockKeepingUnitLabel }

 } union {
     	# Find SKUs where a substance is an active moiety for a substance used in the pharmaceutical product contained in an intermediate packaging (2-step)
		?StockKeepingUnit a cmns-prd:StockKeepingUnit ;
			cmns-dsg:denotes $PackagedMedicinalProduct .
    	?PackagedMedicinalProduct idmp-mprd:contains $OuterPackaging .
      	$OuterPackaging idmp-mprd:contains $InnerPackaing .
		$InnerPackaing 	idmp-mprd:contains $IntermediatePackaging .
    	$IntermediatePackaging idmp-mprd:contains $PharmaceuticalProduct . 
    	$PharmaceuticalProductComposition cmns-dsg:defines $PharmaceuticalProduct .
       	$PharmaceuticalProductComposition idmp-mprd:hasActiveIngredient[
			cmns-rlcmp:isPlayedBy [ 
				^idmp-sub:isActiveMoietyOf|idmp-sub:hasActiveMoiety $Substance 
			]
		] .
		# Make sure that we only return actual substances
		?StockKeepingUnit a/rdfs:subClassOf* cmns-prd:StockKeepingUnit .

		# Optionally, get the name of the substance
		OPTIONAL{?StockKeepingUnit  rdfs:label  ?StockKeepingUnitLabel }
  }

} GROUP BY $StockKeepingUnit