#UC2 CQ 2.1 	Which Marketing Authorization Number(s) does a sellable article (Material in ERP) have?
PREFIX cmns-col:    <https://www.omg.org/spec/Commons/Collections/>
PREFIX cmns-cxtdsg: <https://www.omg.org/spec/Commons/ContextualDesignators/>
PREFIX cmns-rlcmp: <https://www.omg.org/spec/Commons/RolesAndCompositions/>
PREFIX cmns-id: <https://www.omg.org/spec/Commons/Identifiers/>
PREFIX idmp-mprd:   <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/>
PREFIX idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
PREFIX rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?MarketingAuthorizationNumber (SAMPLE(?MarketingAuthorizationNumberLabel) AS ?MarketingAuthorizationNumberName) ?Jurisdiction (SAMPLE(?JurisdictionLabel) AS ?JurisdictionName)


WHERE {
    # Bind Variable substance <$SellalbeArticle>
	# Example for AMLODIPINE: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/NorvascMedicinalProduct>
    BIND( uc2_cq2-1_parameter_1 AS $SellalbeArticle )

    $AuthorizedMedicinalProduct cmns-rlcmp:isPlayedBy $SellalbeArticle .
    $AuthorizedMedicinalProduct idmp-mprd:hasAuthorization $Authorization .
    $Authorization cmns-cxtdsg:isApplicableIn ?Jurisdiction . 
    ?MarketingAuthorizationNumber cmns-id:identifies $Authorization 
     
    # Optionally, get the name of the Authorization Number
    OPTIONAL{?MarketingAuthorizationNumber  rdfs:label  ?MarketingAuthorizationNumberLabel }

        # Optionally, get the name of the Jurisdiction
    OPTIONAL{?Jurisdiction  rdfs:label  ?JurisdictionLabel }

} GROUP BY ?MarketingAuthorizationNumber ?Jurisdiction