#CQ 1:In which materials (package item constituent) is substance <s> used?
# Intended to run on data from AmlodipineExample.rdf

prefix idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
prefix rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:        <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?substanceUri ?substanceType ?substanceLabel

where {

}