#UC2-CQ 1a: In which substances (as active, excipient, packaging) is substance <$TargetSubstance> found?

PREFIX cmns-dsg:    <https://www.omg.org/spec/Commons/Designators/>
PREFIX cmns-pts:    <https://www.omg.org/spec/Commons/PartiesAndSituations/>
PREFIX idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
PREFIX rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?Substance (SAMPLE(?SubstanceLabel) AS ?SubstanceName)

WHERE {
    # Bind Variable substance <$TargetSubstance>
	# Example for AMPLODIPINE: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine>
    BIND( uc2_cq1a_parameter_1 AS $TargetSubstance )

    [] cmns-dsg:defines ?Substance ;
    $Role [
        cmns-pts:isPlayedBy $TargetSubstance
    ] .
  
      # Make sure that we only return actual substances
    ?Substance a/rdfs:subClassOf* idmp-sub:Substance .
     
    # Optionally, get the name of the substance
    OPTIONAL{?Substance  rdfs:label  ?SubstanceLabel }

} GROUP BY ?Substance