# UC-CMC-CQ 3: Which material ID <m> is used in which batch ID <b>?
PREFIX cmns-col:    <https://www.omg.org/spec/Commons/Collections/>
PREFIX cmns-doc:    <https://www.omg.org/spec/Commons/Documents/>
PREFIX cmns-dsg:    <https://www.omg.org/spec/Commons/Designators/>
PREFIX cmns-id: 	<https://www.omg.org/spec/Commons/Identifiers/>
PREFIX cmns-txt:    <https://www.omg.org/spec/Commons/TextDatatype/>
PREFIX idmp-mprd:   <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/>
PREFIX idmp-sub:    <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/>
PREFIX rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:         <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?materialIdentifierValue ?productBatchIdentifierValue

WHERE {
    # Bind Variable medicinal product <$medicinalProduct>
	# Example for Norvasc: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/NorvascMedicinalProduct>
    BIND(uc_cmc_cq4_parameter_1 AS $medicinalProduct )

     $medicinalProduct cmns-doc:specifies ?physicalMedicinalProduct .
     ?physicalMedicinalProduct a idmp-mprd:PhysicalMedicinalProduct .
     ?productBatch cmns-col:isConstituentOf ?physicalMedicinalProduct .
     ?productBatch rdf:type idmp-mprd:Batch .
     ?productBatch cmns-dsg:isSignifiedBy ?productBatchId .
     ?productBatchId cmns-txt:hasTextValue ?productBatchIdentifierValue.
     ?productBatch cmns-col:comprises ?material .
     ?material cmns-id:isIdentifiedBy ?materialIdentifierIRI .
     ?materialIdentifierIRI rdf:type idmp-sub:MaterialIdentifier.
     ?materialIdentifierIRI cmns-txt:hasTextValue ?materialIdentifierValue.
}