# UC-CMC-CQ 2: Which manufacturing site <site> is producing which medicinal product <m>? – FDA would ask for this in the application
PREFIX cmns-doc:     <https://www.omg.org/spec/Commons/Documents/>
PREFIX idmp-mprd:   <https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/>
PREFIX rdf:              <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:             <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:              <http://www.w3.org/2002/07/owl#>


SELECT DISTINCT ?medicinalProduct ?physicalMedicinalProduct ?site

WHERE {
    ?medicinalProduct a idmp-mprd:MedicinalProduct .
    ?medicinalProduct cmns-doc:specifies ?physicalMedicinalProduct .
    ?physicalMedicinalProduct a idmp-mprd:PhysicalMedicinalProduct .
    ?physicalMedicinalProduct idmp-mprd:isProducedAtManufacturingSite ?site .
    ?site a idmp-mprd:ManufacturingSite .

}